import Head from 'next/head'




export default function Home() {
  return (
    <>
      <Head>
        <title>May Madi Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className='bg-teal-700 h-20'>    
        <h1>Hello worldfff</h1>   
        </section>
      </main>
    </>
  )
}
